### ISSUE TITLE
Save cordinates (x,y) and UUIDS/Mac address to mysql db

### ISSUE THREAD

**Issue by muathime** [jarkko-hautakorpi/iBeacon-indoor-positioning-demo#14]
Hi, I have this exact project and it is working fine as described. My aim is to use the beacon coordinates to control movement in a 3d project. I would appreciate much to know how i can save the coordinates and other info such as Mac/uuid to mysql database.

**Comment by muathime** [comment]
am not good in react js but am using php as backend. any leads pls?

**Comment by jarkko-hautakorpi** [comment]
You could listen the beacons with PHP from the Mosquitto with https://github.com/bluerhinos/phpMQTT/blob/master/examples/subscribe.php
or you could just make API with PHP and then call it from ESP32, instead of MQTT publish. The message is already in JSON format, just remove MQTT and do HTTP POST/PUT using the Arduino libraries with ESP32. Anyhow you then need to do trilaterate calculation in PHP, https://github.com/tuupola/trilateration

**Comment by muathime** [comment]
thank you so much Jarkko. solved
