### ISSUE TITLE
 ESP32 is not able to connect to wifi

### ISSUE THREAD

**Issue by futechiot** [jarkko-hautakorpi/iBeacon-indoor-positioning-demo#8]
**Hello There,**

i had done this using another guide.
but your map function is i want to check.

i'm running ESP32 code on ESP32 MH et code is running smoothly.
BUT after BLE scan, ESP 32 is not able to connect to any wifi

is there any change in board.txt file()?
or is there any other configuration i have to do?

Thanks

**Comment by jarkko-hautakorpi** [comment]
No extra configuration needed, the program runs a loop, scan->report->scan->report reconnecting to wifi automatically.

**Comment by mightyDipak** [comment]
Thanks for your reply, I have done this by some modification in code.
Still I am not getting perfect result of location due to placing of gateway, I am using nrf52832 as gateway and send its data to dashboard through mqtt. Can you suggest more rssi filter algorithms. I added Kalman and average filter to get results. Results are considerable good if all gateway are in open space without wall. If wall comes in between beacon and Gateway, then result is not  good show wrong placing. So if you can help me regarding it, then please help me.
So two point:
1) Location of gateway to get more accurate results?
2) overcome the wall effect of beacon?
